resolver: lts-12.26

packages:
- .

# so that `stack build --copy-bins` puts bin here
local-bin-path: .

extra-deps:
- gf-3.10
- cgi-3001.3.0.3 # dependency of gf
- multiset-0.3.4.3

flags:
     # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
