resolver: lts-18.28

packages:
- .

# so that `stack build --copy-bins` puts bin here
local-bin-path: .

extra-deps:
- git: https://github.com/GrammaticalFramework/gf-core
  commit: 810640822dc3047af8fd9d7988e3f2423595c7b2
- multiset-0.3.4.3
- github: GrammaticalFramework/gf-ud
  commit: 1a4a8c1ac08c02895fa886ca20e5e7a706f484e2

flags:
  gf:
    c-runtime: false # this excludes PGF2 module in gf package
    server: false
