resolver: lts-12.26

packages:
- .

# so that `stack build --copy-bins` puts bin here
local-bin-path: .

extra-deps:
- git: https://github.com/GrammaticalFramework/gf-core
  commit: b962bcd178a212f6b3cea6e2d74a2181005a4729
- cgi-3001.3.0.3 # dependency of gf
- multiset-0.3.4.3

flags:
     # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
