concrete ExtractedPGEng of ExtractedPG = ExtractEng ** open MorphoDictEng, ParadigmsEng, MakeStructuralEng in { -- Eng
--lin UseCl cl = UttCl cl ;
lin Educational_objectif_formativo_obiettivi_CN = AdjCN (PositA Educational_A) (UseN objectif_N) ; -- Eng
oper Educational_A = mkA "Educational" ; -- Eng
oper objectif_N = mkN "objectif" ; -- Eng
lin conditional_statement_Conditionale_statements_CN = AdjCN (PositA conditional_A) (UseN statement_N) ; -- Eng
lin dynamic_programme_il_dinamico_programmazione_CN = AdjCN (PositA dynamic_A) (UseN programme_N) ; -- Eng
lin oral_exam_orale_esame_CN = AdjCN (PositA oral_A) (UseN exam_N) ; -- Eng
lin other_course_regulation_altro_regolamento_CN = AdjCN (PositA other_A) (AdjCN (PositA course_A) (UseN regulation_N)) ; -- Eng
oper course_A = mkA "course" ; -- Eng
lin possible_solution_più_possibili_soluzione_CN = AdjCN (PositA possible_A) (UseN solution_N) ; -- Eng
lin practical_training_Esercitazione_CN = AdjCN (PositA practical_A) (UseN training_N) ; -- Eng
lin type_conversion_Typo_conversions_CN = AdjCN (PositA type_A) (UseN conversion_N) ; -- Eng
oper type_A = mkA "type" ; -- Eng
lin Adversary_di_il_avversario_A = Adversary_A ; -- Eng
oper Adversary_A = mkA "Adversary" ; -- Eng
lin Analisi_matematica_Adv = Analisi_Adv ; -- Eng
oper Analisi_Adv = mkAdv "Analisi" ; -- Eng
lin Avoidable_evitabile_A = Avoidable_A ; -- Eng
oper Avoidable_A = mkA "Avoidable" ; -- Eng
lin Boolean_di_Boola_A = Boolean_A ; -- Eng
oper Boolean_A = mkA "Boolean" ; -- Eng
lin Boolean_Booleane_A = Boolean_A ; -- Eng
oper Boolean_A = mkA "Boolean" ; -- Eng
lin Collaborative_collaborativo_A = Collaborative_A ; -- Eng
oper Collaborative_A = mkA "Collaborative" ; -- Eng
lin Computational_Computazionale_A = Computational_A ; -- Eng
oper Computational_A = mkA "Computational" ; -- Eng
lin DF_Traversal_algoritmo_A = DF_Traversal_A ; -- Eng
oper DF_Traversal_A = mkA "DF" ; -- Eng
lin Decidable_decidibile_A = Decidable_A ; -- Eng
oper Decidable_A = mkA "Decidable" ; -- Eng
lin other_information_altro_informazione_NP = DetCN other_Det (UseN information_N) ; -- Eng
oper other_Det = mkDet "other" ; -- Eng
lin some_further_questions_alcuno_domanda_di_teoria_NP = DetCN some_Det (AdjCN (PositA further_A) (UseN questions_N)) ; -- Eng
oper some_Det = mkDet "some" ; -- Eng
oper questions_N = mkN "questions" ; -- Eng
lin the_oral_exam_il_orale_prova_NP = DetCN the_Det (AdjCN (PositA oral_A) (UseN exam_N)) ; -- Eng
lin the_oral_examine_il_orala_NP = DetCN the_Det (AdjCN (PositA oral_A) (UseN examine_N)) ; -- Eng
oper examine_N = mkN "examine" ; -- Eng
lin the_goal_possess_this_exam_tale_prova_NP = DetCN the_Det (PrepCN (UseN goal_N) (PrepNP possess_Prep (DetCN this_Det (UseN exam_N)))) ; -- Eng
lin the_course_il_corso_NP = DetCN the_Det (UseN course_N) ; -- Eng
lin the_course_il_insegnamento_NP = DetCN the_Det (UseN course_N) ; -- Eng
lin the_exam_il_esame_NP = DetCN the_Det (UseN exam_N) ; -- Eng
lin the_finite_il_modello_NP = DetCN the_Det (UseN finite_N) ; -- Eng
oper finite_N = mkN "finite" ; -- Eng
lin the_student_il_accesso_NP = DetCN the_Det (UseN student_N) ; -- Eng
lin the_student_il_studente_NP = DetCN the_Det (UseN student_N) ; -- Eng
lin this_notion_tale_nozione_NP = DetCN this_Det (UseN notion_N) ; -- Eng
lin Didactic_didattico_A = Didactic_A ; -- Eng
oper Didactic_A = mkA "Didactic" ; -- Eng
lin Didactic_dispense_Adv = Didactic_Adv ; -- Eng
oper Didactic_Adv = mkAdv "Didactic" ; -- Eng
lin Differential_differenziale_A = Differential_A ; -- Eng
oper Differential_A = mkA "Differential" ; -- Eng
lin Dimensional_dimensionale_A = Dimensional_A ; -- Eng
oper Dimensional_A = mkA "Dimensional" ; -- Eng
lin Educational_obiettivi_A = Educational_A ; -- Eng
oper Educational_A = mkA "Educational" ; -- Eng
lin English_inglendere_A = English_A ; -- Eng
lin English_italiano_A = English_A ; -- Eng
lin Epistemological_epistemologico_A = Epistemological_A ; -- Eng
oper Epistemological_A = mkA "Epistemological" ; -- Eng
lin French_inglese_A = French_A ; -- Eng
lin II_II_A = II_A ; -- Eng
oper II_A = mkA "II" ; -- Eng
lin Inf_INF_Adv = Inf_Adv ; -- Eng
oper Inf_Adv = mkAdv "Inf" ; -- Eng
lin Input_Input_Prep = Input_Prep ; -- Eng
oper Input_Prep = mkPrep "Input" ; -- Eng
lin Integral_Integrale_A = Integral_A ; -- Eng
oper Integral_A = mkA "Integral" ; -- Eng
lin Integral_proprietà_A = Integral_A ; -- Eng
oper Integral_A = mkA "Integral" ; -- Eng
lin Italia_ITALIANO_Prep = Italia_Prep ; -- Eng
oper Italia_Prep = mkPrep "Italia" ; -- Eng
lin Italian_ITALIANO_A = Italian_A ; -- Eng
lin Italian_inglese_A = Italian_A ; -- Eng
lin Italiano_ITALIANO_Det = Italiano_Det ; -- Eng
oper Italiano_Det = mkDet "Italiano" ; -- Eng
lin Meaningful_significativo_A = Meaningful_A ; -- Eng
oper Meaningful_A = mkA "Meaningful" ; -- Eng
lin Np_completo_Adv = Np_Adv ; -- Eng
oper Np_Adv = mkAdv "Np" ; -- Eng
lin Obbligatorio_Obbligatorio_Adv = Obbligatorio_Adv ; -- Eng
oper Obbligatorio_Adv = mkAdv "Obbligatorio" ; -- Eng
lin Optional_orale_esame_A = Optional_A ; -- Eng
oper Optional_A = mkA "Optional" ; -- Eng
lin Output_Output_Prep = Output_Prep ; -- Eng
oper Output_Prep = mkPrep "Output" ; -- Eng
lin Partial_parziale_A = Partial_A ; -- Eng
oper Partial_A = mkA "Partial" ; -- Eng
lin Lecture_in_class_frontale_lezione_CN = PrepCN (UseN Lecture_N) (PrepNP in_Prep (PluralNP (UseN class_N))) ; -- Eng
oper Lecture_N = mkN "Lecture" ; -- Eng
lin attendance_possess_lesson_Frequenza_CN = PrepCN (UseN attendance_N) (PrepNP possess_Prep (PluralNP (UseN lesson_N))) ; -- Eng
lin type_possess_learn_activity_tipo_attività_CN = PrepCN (UseN type_N) (PrepNP possess_Prep (PluralNP (AdjCN (PositA learn_A) (UseN activity_N)))) ; -- Eng
oper learn_A = mkA "learn" ; -- Eng
lin at_the_library_in_biblioteca_PP = PrepNP at_Prep (DetCN the_Det (UseN library_N)) ; -- Eng
lin during_the_course_prova_PP = PrepNP during_Prep (DetCN the_Det (UseN course_N)) ; -- Eng
lin in_some_case_in_alcuno_caso_PP = PrepNP in_Prep (DetCN some_Det (UseN case_N)) ; -- Eng
oper some_Det = mkDet "some" ; -- Eng
lin in_numerical_analysis_Basics_a_il_concetto_di_base_di_il_numerico_analisi_PP = PrepNP in_Prep (MassNP (AdvCN (AdjCN (PositA numerical_A) (UseN analysis_N)) Basics_Adv)) ; -- Eng
oper Basics_Adv = mkAdv "Basics" ; -- Eng
lin in_numerical_analysis_Basics_di_base_di_il_numerico_analisi_PP = PrepNP in_Prep (MassNP (AdvCN (AdjCN (PositA numerical_A) (UseN analysis_N)) Basics_Adv)) ; -- Eng
oper Basics_Adv = mkAdv "Basics" ; -- Eng
lin in_binary_in_binario_PP = PrepNP in_Prep (MassNP (UseN binary_N)) ; -- Eng
lin in_class_a_lezione_PP = PrepNP in_Prep (MassNP (UseN class_N)) ; -- Eng
lin in_various_sector_in_vario_settore_PP = PrepNP in_Prep (PluralNP (AdjCN (PositA various_A) (UseN sector_N))) ; -- Eng
lin in_class_frontale_PP = PrepNP in_Prep (PluralNP (UseN class_N)) ; -- Eng
lin in_informatics_in_informatico_PP = PrepNP in_Prep (PluralNP (UseN informatics_N)) ; -- Eng
oper informatics_N = mkN "informatics" ; -- Eng
lin in_Informatics_triennale_PP = PrepNP in_Prep (UsePN Informatics_PN) ; -- Eng
oper Informatics_PN = mkPN "Informatics" ; -- Eng
lin leader_election_di_impossibilità_PP = PrepNP leader_Prep (UsePN election_PN) ; -- Eng
oper leader_Prep = mkPrep "leader" ; -- Eng
oper election_PN = mkPN "election" ; -- Eng
lin over_hypercube_su_il_ipercubio_PP = PrepNP over_Prep (PluralNP (UseN hypercube_N)) ; -- Eng
oper hypercube_N = mkN "hypercube" ; -- Eng
lin possess_a_tutor_di_a_tutor_PP = PrepNP possess_Prep (DetCN a_Det (UseN tutor_N)) ; -- Eng
lin possess_the_collaboration_possess_expert_di_esperto_PP = PrepNP possess_Prep (DetCN the_Det (PrepCN (UseN collaboration_N) (PrepNP possess_Prep (PluralNP (UseN expert_N))))) ; -- Eng
lin possess_the_course_di_il_corso_PP = PrepNP possess_Prep (DetCN the_Det (UseN course_N)) ; -- Eng
lin possess_the_method_di_il_linguaggio_PP = PrepNP possess_Prep (DetCN the_Det (UseN method_N)) ; -- Eng
lin possess_the_object_di_il_oggetto_PP = PrepNP possess_Prep (DetCN the_Det (UseN object_N)) ; -- Eng
lin possess_the_project_di_il_progetto_PP = PrepNP possess_Prep (DetCN the_Det (UseN project_N)) ; -- Eng
lin possess_the_student_di_il_studente_in_difficoltà_PP = PrepNP possess_Prep (DetCN the_Det (UseN student_N)) ; -- Eng
lin possess_deep_learning_learning_PP = PrepNP possess_Prep (MassNP (AdjCN (PositA deep_A) (UseN learning_N))) ; -- Eng
lin possess_Flooding_di_il_Algoritmo_loodinina_PP = PrepNP possess_Prep (MassNP (UseN Flooding_N)) ; -- Eng
oper Flooding_N = mkN "Flooding" ; -- Eng
lin possess_computability_di_il_computabilità_PP = PrepNP possess_Prep (MassNP (UseN computability_N)) ; -- Eng
oper computability_N = mkN "computability" ; -- Eng
lin possess_help_di_aiuto_PP = PrepNP possess_Prep (MassNP (UseN help_N)) ; -- Eng
lin possess_programming_di_il_programmazione_PP = PrepNP possess_Prep (MassNP (UseN programming_N)) ; -- Eng
lin possess_saturation_tramite_saturazione_PP = PrepNP possess_Prep (MassNP (UseN saturation_N)) ; -- Eng
lin possess_classic_solution_di_soluzione_PP = PrepNP possess_Prep (PluralNP (AdjCN (PositA classic_A) (UseN solution_N))) ; -- Eng
lin possess_professional_interface_con_interfaccia_di_professionale_tipo_PP = PrepNP possess_Prep (PluralNP (AdjCN (PositA professional_A) (UseN interface_N))) ; -- Eng
lin possess_object_for_reference_di_oggetto_PP = PrepNP possess_Prep (PluralNP (PrepCN (UseN object_N) (PrepNP for_Prep (MassNP (UseN reference_N))))) ; -- Eng
lin possess_function_di_funzione_PP = PrepNP possess_Prep (PluralNP (UseN function_N)) ; -- Eng
lin possess_ALGORITHMS_di_PP = PrepNP possess_Prep (UsePN ALGORITHMS_PN) ; -- Eng
oper ALGORITHMS_PN = mkPN "ALGORITHMS" ; -- Eng
lin to_the_assigned_project_il_scritto_prova_PP = PrepNP to_Prep (DetCN the_Det (AdjCN (PositA assigned_A) (UseN project_N))) ; -- Eng
oper assigned_A = mkA "assigned" ; -- Eng
lin to_student_in_difficulty_con_studente_PP = PrepNP to_Prep (PluralNP (PrepCN (UseN student_N) (PrepNP in_Prep (MassNP (UseN difficulty_N))))) ; -- Eng
lin with_the_basic_concept_possess_programming_con_il_concetto_di_il_programmazione_PP = PrepNP with_Prep (DetCN the_Det (PrepCN (AdjCN (PositA basic_A) (UseN concept_N)) (PrepNP possess_Prep (MassNP (UseN programming_N))))) ; -- Eng
lin with_slide_con_slide_in_inglese_PP = PrepNP with_Prep (PluralNP (UseN slide_N)) ; -- Eng
lin with_GCC_con_GCC_PP = PrepNP with_Prep (UsePN GCC_PN) ; -- Eng
oper GCC_PN = mkPN "GCC" ; -- Eng
lin with_GDB_con_GDB_PP = PrepNP with_Prep (UsePN GDB_PN) ; -- Eng
oper GDB_PN = mkPN "GDB" ; -- Eng
lin Procedural_procedurale_A = Procedural_A ; -- Eng
oper Procedural_A = mkA "Procedural" ; -- Eng
lin Recursive_Ricorsive_A = Recursive_A ; -- Eng
oper Recursive_A = mkA "Recursive" ; -- Eng
lin Riemann_di_Riemann_Adv = Riemann_Adv ; -- Eng
oper Riemann_Adv = mkAdv "Riemann" ; -- Eng
lin Structured_strutturato_A = Structured_A ; -- Eng
oper Structured_A = mkA "Structured" ; -- Eng
lin Traversal_di_il_attraversamento_A = Traversal_A ; -- Eng
oper Traversal_A = mkA "Traversal" ; -- Eng
lin Unsolvable_insolubile_A = Unsolvable_A ; -- Eng
oper Unsolvable_A = mkA "Unsolvable" ; -- Eng
lin Alphabet_Alfabeto_CN = UseN Alphabet_N ; -- Eng
oper Alphabet_N = mkN "Alphabet" ; -- Eng
lin Arrays_Arrays_CN = UseN Arrays_N ; -- Eng
oper Arrays_N = mkN "Arrays" ; -- Eng
lin Attività_formativo_CN = UseN Attività_N ; -- Eng
oper Attività_N = mkN "Attività" ; -- Eng
lin Axiom_Assiome_CN = UseN Axiom_N ; -- Eng
oper Axiom_N = mkN "Axiom" ; -- Eng
lin Broadcast_esempio_CN = UseN Broadcast_N ; -- Eng
oper Broadcast_N = mkN "Broadcast" ; -- Eng
lin Broadcast_problema_CN = UseN Broadcast_N ; -- Eng
oper Broadcast_N = mkN "Broadcast" ; -- Eng
lin Compilation_di_compilazione_CN = UseN Compilation_N ; -- Eng
oper Compilation_N = mkN "Compilation" ; -- Eng
lin Complexity_di_il_complessità_CN = UseN Complexity_N ; -- Eng
oper Complexity_N = mkN "Complexity" ; -- Eng
lin Complexity_complessità_CN = UseN Complexity_N ; -- Eng
oper Complexity_N = mkN "Complexity" ; -- Eng
lin Computability_Computability_CN = UseN Computability_N ; -- Eng
oper Computability_N = mkN "Computability" ; -- Eng
lin Content_contenere_CN = UseN Content_N ; -- Eng
oper Content_N = mkN "Content" ; -- Eng
lin Correctness_costo_CN = UseN Correctness_N ; -- Eng
oper Correctness_N = mkN "Correctness" ; -- Eng
lin Correctness_Correttezza_CN = UseN Correctness_N ; -- Eng
oper Correctness_N = mkN "Correctness" ; -- Eng
lin Curriculuy_Curriculum_CN = UseN Curriculuy_N ; -- Eng
oper Curriculuy_N = mkN "Curriculuy" ; -- Eng
lin Cut_Tallo_CN = UseN Cut_N ; -- Eng
oper Cut_N = mkN "Cut" ; -- Eng
lin Ecceptions_Eccezioni_CN = UseN Ecceptions_N ; -- Eng
oper Ecceptions_N = mkN "Ecceptions" ; -- Eng
lin Encapsulation_Incapsulamento_CN = UseN Encapsulation_N ; -- Eng
oper Encapsulation_N = mkN "Encapsulation" ; -- Eng
lin Flooding_loodinina_CN = UseN Flooding_N ; -- Eng
oper Flooding_N = mkN "Flooding" ; -- Eng
lin Function_funzione_CN = UseN Function_N ; -- Eng
oper Function_N = mkN "Function" ; -- Eng
lin Function_studio_CN = UseN Function_N ; -- Eng
oper Function_N = mkN "Function" ; -- Eng
lin Function_Functions_CN = UseN Function_N ; -- Eng
oper Function_N = mkN "Function" ; -- Eng
lin Geometry_Geometria_CN = UseN Geometry_N ; -- Eng
oper Geometry_N = mkN "Geometry" ; -- Eng
lin Informatics_informatica_CN = UseN Informatics_N ; -- Eng
oper Informatics_N = mkN "Informatics" ; -- Eng
lin Karp_Cook_CN = UseN Karp_N ; -- Eng
oper Karp_N = mkN "Karp" ; -- Eng
lin L_classe_CN = UseN L_N ; -- Eng
oper L_N = mkN "L" ; -- Eng
lin Lecture_lezione_CN = UseN Lecture_N ; -- Eng
oper Lecture_N = mkN "Lecture" ; -- Eng
lin Lecturer_Docere_CN = UseN Lecturer_N ; -- Eng
oper Lecturer_N = mkN "Lecturer" ; -- Eng
lin Lecturer_responsabile_Docente_CN = UseN Lecturer_N ; -- Eng
oper Lecturer_N = mkN "Lecturer" ; -- Eng
lin Lectures_frontale_lezione_CN = UseN Lectures_N ; -- Eng
oper Lectures_N = mkN "Lectures" ; -- Eng
lin Lectures_lezione_CN = UseN Lectures_N ; -- Eng
oper Lectures_N = mkN "Lectures" ; -- Eng
lin Literal_Literals_CN = UseN Literal_N ; -- Eng
oper Literal_N = mkN "Literal" ; -- Eng
lin Loops_Loops_CN = UseN Loops_N ; -- Eng
oper Loops_N = mkN "Loops" ; -- Eng
lin Maggioli_editore_CN = UseN Maggioli_N ; -- Eng
oper Maggioli_N = mkN "Maggioli" ; -- Eng
lin Maxima_autovalore_CN = UseN Maxima_N ; -- Eng
oper Maxima_N = mkN "Maxima" ; -- Eng
lin Opzionale_Optional_CN = UseN Opzionale_N ; -- Eng
oper Opzionale_N = mkN "Opzionale" ; -- Eng
lin Pointers_Pointers_CN = UseN Pointers_N ; -- Eng
oper Pointers_N = mkN "Pointers" ; -- Eng
lin Polymorphism_Polimorfismo_CN = UseN Polymorphism_N ; -- Eng
oper Polymorphism_N = mkN "Polymorphism" ; -- Eng
lin Saturation_di_il_saturazione_CN = UseN Saturation_N ; -- Eng
oper Saturation_N = mkN "Saturation" ; -- Eng
lin Sector_settore_CN = UseN Sector_N ; -- Eng
oper Sector_N = mkN "Sector" ; -- Eng
lin Shout_Shout_CN = UseN Shout_N ; -- Eng
oper Shout_N = mkN "Shout" ; -- Eng
lin Socket_Socket_CN = UseN Socket_N ; -- Eng
oper Socket_N = mkN "Socket" ; -- Eng
lin Statement_Statements_CN = UseN Statement_N ; -- Eng
oper Statement_N = mkN "Statement" ; -- Eng
lin Task_Compito_CN = UseN Task_N ; -- Eng
oper Task_N = mkN "Task" ; -- Eng
lin Tree_costruzione_CN = UseN Tree_N ; -- Eng
oper Tree_N = mkN "Tree" ; -- Eng
lin Unsolvability_Unsolvability_CN = UseN Unsolvability_N ; -- Eng
oper Unsolvability_N = mkN "Unsolvability" ; -- Eng
lin ability_capacità_CN = UseN ability_N ; -- Eng
lin ability_adattare_CN = UseN ability_N ; -- Eng
lin absence_prova_CN = UseN absence_N ; -- Eng
lin acquisition_metodo_CN = UseN acquisition_N ; -- Eng
lin activity_attività_CN = UseN activity_N ; -- Eng
lin activity_piattaforma_CN = UseN activity_N ; -- Eng
lin addition_esposizione_CN = UseN addition_N ; -- Eng
lin aim_obiettivo_CN = UseN aim_N ; -- Eng
lin algebra_lineare_CN = UseN algebra_N ; -- Eng
lin algebrà_algebra_CN = UseN algebrà_N ; -- Eng
oper algebrà_N = mkN "algebrà" ; -- Eng
lin algebrà_proprietaa_CN = UseN algebrà_N ; -- Eng
oper algebrà_N = mkN "algebrà" ; -- Eng
lin algorithm_Algoritmo_CN = UseN algorithm_N ; -- Eng
lin algorithm_ricerca_CN = UseN algorithm_N ; -- Eng
lin algorithm_DF_Traversal_CN = UseN algorithm_N ; -- Eng
lin algorithm_Algoritmo_CN = UseN algorithm_N ; -- Eng
lin algorithy_Flooding_CN = UseN algorithy_N ; -- Eng
oper algorithy_N = mkN "algorithy" ; -- Eng
lin analog_informazione_CN = UseN analog_N ; -- Eng
lin analysis_base_CN = UseN analysis_N ; -- Eng
lin analysis_concetto_CN = UseN analysis_N ; -- Eng
lin analysis_vista_CN = UseN analysis_N ; -- Eng
lin analysis_combinatorio_CN = UseN analysis_N ; -- Eng
lin application_applicazione_CN = UseN application_N ; -- Eng
lin application_programma_CN = UseN application_N ; -- Eng
lin approach_approccio_CN = UseN approach_N ; -- Eng
lin approximation_approssimazione_CN = UseN approximation_N ; -- Eng
lin aspect_aspetto_CN = UseN aspect_N ; -- Eng
lin assignment_casa_CN = UseN assignment_N ; -- Eng
lin attention_attenzione_CN = UseN attention_N ; -- Eng
lin average_media_CN = UseN average_N ; -- Eng
lin base_formazione_CN = UseN base_N ; -- Eng
lin base_studente_CN = UseN base_N ; -- Eng
lin basics_finire_CN = UseN basics_N ; -- Eng
lin behavior_comportamento_CN = UseN behavior_N ; -- Eng
lin behaviorist_di_conoscenza_CN = UseN behaviorist_N ; -- Eng
lin binary_binario_CN = UseN binary_N ; -- Eng
lin bounds_bounds_CN = UseN bounds_N ; -- Eng
oper bounds_N = mkN "bounds" ; -- Eng
lin calcolabilità_linguaggio_CN = UseN calcolabilità_N ; -- Eng
oper calcolabilità_N = mkN "calcolabilità" ; -- Eng
lin calculus_Calcolo_CN = UseN calculus_N ; -- Eng
lin case_caso_CN = UseN case_N ; -- Eng
lin church_secondo_Church_CN = UseN church_N ; -- Eng
lin circuit_di_il_circuita_CN = UseN circuit_N ; -- Eng
lin class_classe_CN = UseN class_N ; -- Eng
lin class_lezione_CN = UseN class_N ; -- Eng
lin class_p_CN = UseN class_N ; -- Eng
lin class_classe_CN = UseN class_N ; -- Eng
lin classification_classificazione_CN = UseN classification_N ; -- Eng
lin clustering_clustering_CN = UseN clustering_N ; -- Eng
oper clustering_N = mkN "clustering" ; -- Eng
lin code_insegnamento_CN = UseN code_N ; -- Eng
lin collaboration_esperto_CN = UseN collaboration_N ; -- Eng
lin communication_comunicazione_CN = UseN communication_N ; -- Eng
lin completeness_problema_CN = UseN completeness_N ; -- Eng
lin composition_generalità_CN = UseN composition_N ; -- Eng
lin computability_computabilità_CN = UseN computability_N ; -- Eng
oper computability_N = mkN "computability" ; -- Eng
lin computabilty_Calcolabilità_CN = UseN computabilty_N ; -- Eng
oper computabilty_N = mkN "computabilty" ; -- Eng
lin computer_Didattica_CN = UseN computer_N ; -- Eng
lin computer_base_CN = UseN computer_N ; -- Eng
lin concept_concetto_CN = UseN concept_N ; -- Eng
lin concept_logica_CN = UseN concept_N ; -- Eng
lin connector_Connettore_CN = UseN connector_N ; -- Eng
oper connector_N = mkN "connector" ; -- Eng
lin consist_esame_CN = UseN consist_N ; -- Eng
oper consist_N = mkN "consist" ; -- Eng
lin consist_consistere_CN = UseN consist_N ; -- Eng
oper consist_N = mkN "consist" ; -- Eng
lin consist_costituire_CN = UseN consist_N ; -- Eng
oper consist_N = mkN "consist" ; -- Eng
lin construction_hocetera_CN = UseN construction_N ; -- Eng
lin continuity_continuità_CN = UseN continuity_N ; -- Eng
lin control_di_controllo_CN = UseN control_N ; -- Eng
lin conversion_conversions_CN = UseN conversion_N ; -- Eng
lin cost_miglioramento_CN = UseN cost_N ; -- Eng
lin cost_stabilità_CN = UseN cost_N ; -- Eng
lin cost_costo_CN = UseN cost_N ; -- Eng
lin course_conferenza_CN = UseN course_N ; -- Eng
lin course_corso_CN = UseN course_N ; -- Eng
lin course_insegnamento_CN = UseN course_N ; -- Eng
lin course_laurea_CN = UseN course_N ; -- Eng
lin course_tutto_CN = UseN course_N ; -- Eng
lin cycle_ciclo_CN = UseN cycle_N ; -- Eng
lin cycles_assenza_CN = UseN cycles_N ; -- Eng
oper cycles_N = mkN "cycles" ; -- Eng
lin definition_definizione_CN = UseN definition_N ; -- Eng
lin degree_elemento_CN = UseN degree_N ; -- Eng
lin derive_derivazione_CN = UseN derive_N ; -- Eng
oper derive_N = mkN "derive" ; -- Eng
lin design_progettazione_CN = UseN design_N ; -- Eng
lin detection_anomaly_CN = UseN detection_N ; -- Eng
lin development_svolgimento_CN = UseN development_N ; -- Eng
lin didactics_Didattica_CN = UseN didactics_N ; -- Eng
oper didactics_N = mkN "didactics" ; -- Eng
lin difficulty_difficoltà_CN = UseN difficulty_N ; -- Eng
lin directife_direttive_CN = UseN directife_N ; -- Eng
oper directife_N = mkN "directife" ; -- Eng
lin disability_studente_CN = UseN disability_N ; -- Eng
lin discipline_informatico_CN = UseN discipline_N ; -- Eng
lin discussion_discussione_CN = UseN discussion_N ; -- Eng
lin discussion_consistere_CN = UseN discussion_N ; -- Eng
lin e_concetto_CN = UseN e_N ; -- Eng
oper e_N = mkN "e" ; -- Eng
lin e_fondamente_CN = UseN e_N ; -- Eng
oper e_N = mkN "e" ; -- Eng
lin edition_to_CN = UseN edition_N ; -- Eng
lin edizione_tecnico_CN = UseN edizione_N ; -- Eng
oper edizione_N = mkN "edizione" ; -- Eng
lin end_base_CN = UseN end_N ; -- Eng
lin environment_ambiente_CN = UseN environment_N ; -- Eng
lin equation_Equazione_CN = UseN equation_N ; -- Eng
lin exam_di_svolgimento_CN = UseN exam_N ; -- Eng
lin exam_esame_CN = UseN exam_N ; -- Eng
lin exam_orale_CN = UseN exam_N ; -- Eng
lin exam_prova_CN = UseN exam_N ; -- Eng
lin exam_consistere_CN = UseN exam_N ; -- Eng
lin exam_scrivere_CN = UseN exam_N ; -- Eng
lin exam_opzionale_CN = UseN exam_N ; -- Eng
lin exam_orale_CN = UseN exam_N ; -- Eng
lin examination_prova_CN = UseN examination_N ; -- Eng
lin examination_orale_CN = UseN examination_N ; -- Eng
lin example_Broadcast_CN = UseN example_N ; -- Eng
lin examples_esempe_CN = UseN examples_N ; -- Eng
oper examples_N = mkN "examples" ; -- Eng
lin examples_esempio_CN = UseN examples_N ; -- Eng
oper examples_N = mkN "examples" ; -- Eng
lin exay_il_esame_CN = UseN exay_N ; -- Eng
oper exay_N = mkN "exay" ; -- Eng
lin exercise_Esercitazione_CN = UseN exercise_N ; -- Eng
lin exercise_argomento_CN = UseN exercise_N ; -- Eng
lin exercise_esercizio_CN = UseN exercise_N ; -- Eng
lin exercise_verta_CN = UseN exercise_N ; -- Eng
lin explore_Esplorazione_CN = UseN explore_N ; -- Eng
oper explore_N = mkN "explore" ; -- Eng
lin expression_istruzione_CN = UseN expression_N ; -- Eng
lin expression_Expressions_CN = UseN expression_N ; -- Eng
lin extremes_successione_CN = UseN extremes_N ; -- Eng
oper extremes_N = mkN "extremes" ; -- Eng
lin finite_modello_CN = UseN finite_N ; -- Eng
oper finite_N = mkN "finite" ; -- Eng
lin fisica_formazione_CN = UseN fisica_N ; -- Eng
oper fisica_N = mkN "fisica" ; -- Eng
lin formativà_attività_CN = UseN formativà_N ; -- Eng
oper formativà_N = mkN "formativà" ; -- Eng
lin function_caratteristica_CN = UseN function_N ; -- Eng
lin function_funzione_CN = UseN function_N ; -- Eng
lin function_funzioni_CN = UseN function_N ; -- Eng
lin function_teorema_CN = UseN function_N ; -- Eng
lin fundamental_metodo_CN = UseN fundamental_N ; -- Eng
lin goal_prova_CN = UseN goal_N ; -- Eng
lin grade_voto_CN = UseN grade_N ; -- Eng
lin graph_grafo_CN = UseN graph_N ; -- Eng
lin graph_Broadcast_CN = UseN graph_N ; -- Eng
lin hand_di_il_destrare_mano_CN = UseN hand_N ; -- Eng
lin help_aiuto_CN = UseN help_N ; -- Eng
lin history_storia_CN = UseN history_N ; -- Eng
lin hour_ora_CN = UseN hour_N ; -- Eng
lin hour_ore_CN = UseN hour_N ; -- Eng
lin hour_scritto_CN = UseN hour_N ; -- Eng
lin hypercube_ipercubio_CN = UseN hypercube_N ; -- Eng
oper hypercube_N = mkN "hypercube" ; -- Eng
lin hypercube_Ipercubi_CN = UseN hypercube_N ; -- Eng
oper hypercube_N = mkN "hypercube" ; -- Eng
lin identifier_Identificatore_CN = UseN identifier_N ; -- Eng
lin impossibility_a_albero_CN = UseN impossibility_N ; -- Eng
lin improvement_miglioramento_CN = UseN improvement_N ; -- Eng
lin inequality_disequazione_CN = UseN inequality_N ; -- Eng
lin informatiche_Disciplina_CN = UseN informatiche_N ; -- Eng
oper informatiche_N = mkN "informatiche" ; -- Eng
lin informatics_informatico_CN = UseN informatics_N ; -- Eng
oper informatics_N = mkN "informatics" ; -- Eng
lin information_informazione_CN = UseN information_N ; -- Eng
lin inheritance_Ereditarietà_CN = UseN inheritance_N ; -- Eng
lin initiator_iniziatore_CN = UseN initiator_N ; -- Eng
oper initiator_N = mkN "initiator" ; -- Eng
lin integral_doppio_CN = UseN integral_N ; -- Eng
lin interface_interfaccia_CN = UseN interface_N ; -- Eng
lin introduction_introduzione_CN = UseN introduction_N ; -- Eng
lin introduction_linguaggio_CN = UseN introduction_N ; -- Eng
lin introduction_introduzione_CN = UseN introduction_N ; -- Eng
lin issue_tematica_CN = UseN issue_N ; -- Eng
lin knowledge_conoscenza_CN = UseN knowledge_N ; -- Eng
lin lab_aula_CN = UseN lab_N ; -- Eng
lin language_insegnamento_CN = UseN language_N ; -- Eng
lin language_introduzione_CN = UseN language_N ; -- Eng
lin language_programmazione_CN = UseN language_N ; -- Eng
lin language_Basics_CN = UseN language_N ; -- Eng
lin language_linguaggio_CN = UseN language_N ; -- Eng
lin language_interpretare_CN = UseN language_N ; -- Eng
lin last_tempo_CN = UseN last_N ; -- Eng
lin learning_Apprendimento_CN = UseN learning_N ; -- Eng
lin lecture_lezione_CN = UseN lecture_N ; -- Eng
lin lecture_importantissimo_CN = UseN lecture_N ; -- Eng
lin lesson_lezione_CN = UseN lesson_N ; -- Eng
lin level_base_CN = UseN level_N ; -- Eng
lin level_elaboratore_CN = UseN level_N ; -- Eng
lin level_livello_CN = UseN level_N ; -- Eng
lin levin_Cook_CN = UseN levin_N ; -- Eng
oper levin_N = mkN "levin" ; -- Eng
lin library_biblioteca_CN = UseN library_N ; -- Eng
lin limit_limite_CN = UseN limit_N ; -- Eng
lin limit_limite_CN = UseN limit_N ; -- Eng
lin limit_continua_CN = UseN limit_N ; -- Eng
lin list_dinamiche_CN = UseN list_N ; -- Eng
lin list_Lista_CN = UseN list_N ; -- Eng
lin machine_macchina_CN = UseN machine_N ; -- Eng
lin management_Dynamic_CN = UseN management_N ; -- Eng
lin marks_voto_CN = UseN marks_N ; -- Eng
oper marks_N = mkN "marks" ; -- Eng
lin mathematics_matematica_CN = UseN mathematics_N ; -- Eng
lin means_grafo_CN = UseN means_N ; -- Eng
lin means_minimo_CN = UseN means_N ; -- Eng
lin memory_memoria_CN = UseN memory_N ; -- Eng
lin method_deep_CN = UseN method_N ; -- Eng
lin method_linguaggio_CN = UseN method_N ; -- Eng
lin method_metodi_CN = UseN method_N ; -- Eng
lin method_metodo_CN = UseN method_N ; -- Eng
lin minute_minuto_CN = UseN minute_N ; -- Eng
lin misconception_misconcezione_CN = UseN misconception_N ; -- Eng
lin misconception_il_CN = UseN misconception_N ; -- Eng
lin mistake_errore_CN = UseN mistake_N ; -- Eng
lin modality_modalità_CN = UseN modality_N ; -- Eng
lin model_modello_CN = UseN model_N ; -- Eng
lin model_trasmissione_CN = UseN model_N ; -- Eng
lin module_modulo_CN = UseN module_N ; -- Eng
lin name_corso_CN = UseN name_N ; -- Eng
lin net_Jare_CN = UseN net_N ; -- Eng
lin network_Networks_CN = UseN network_N ; -- Eng
lin no_nessuno_CN = UseN no_N ; -- Eng
oper no_N = mkN "no" ; -- Eng
lin notion_nozione_CN = UseN notion_N ; -- Eng
lin object_oggetto_CN = UseN object_N ; -- Eng
lin objectif_formativo_CN = UseN objectif_N ; -- Eng
oper objectif_N = mkN "objectif" ; -- Eng
lin obstacle_ostacolo_CN = UseN obstacle_N ; -- Eng
lin operator_operators_CN = UseN operator_N ; -- Eng
lin orientation_orientamento_CN = UseN orientation_N ; -- Eng
lin part_lo_scrivere_CN = UseN part_N ; -- Eng
lin part_series_CN = UseN part_N ; -- Eng
lin pattern_schema_CN = UseN pattern_N ; -- Eng
lin platform_attività_CN = UseN platform_N ; -- Eng
lin platform_piattaforma_CN = UseN platform_N ; -- Eng
lin point_prova_CN = UseN point_N ; -- Eng
lin possibility_possibilità_CN = UseN possibility_N ; -- Eng
lin prerequisite_Prerequisire_CN = UseN prerequisite_N ; -- Eng
lin prerequisite_prerequisito_CN = UseN prerequisite_N ; -- Eng
lin principle_principio_CN = UseN principle_N ; -- Eng
lin problem_di_il_arresto_CN = UseN problem_N ; -- Eng
lin problem_Probelma_CN = UseN problem_N ; -- Eng
lin problem_applicazione_CN = UseN problem_N ; -- Eng
lin problem_problema_CN = UseN problem_N ; -- Eng
lin problem_problema_CN = UseN problem_N ; -- Eng
lin problem_Decimo_CN = UseN problem_N ; -- Eng
lin program_elaboratore_CN = UseN program_N ; -- Eng
lin program_programma_CN = UseN program_N ; -- Eng
lin programme_programmazione_CN = UseN programme_N ; -- Eng
lin programming_di_il_programmazione_a_oggetto_CN = UseN programming_N ; -- Eng
lin programming_base_CN = UseN programming_N ; -- Eng
lin programming_comprensione_CN = UseN programming_N ; -- Eng
lin programming_elemento_CN = UseN programming_N ; -- Eng
lin programming_istruzione_CN = UseN programming_N ; -- Eng
lin programming_programmazione_CN = UseN programming_N ; -- Eng
lin project_progetto_CN = UseN project_N ; -- Eng
lin project_trentesimo_CN = UseN project_N ; -- Eng
lin project_assegnare_CN = UseN project_N ; -- Eng
lin projector_lavagna_CN = UseN projector_N ; -- Eng
lin property_caratteristica_CN = UseN property_N ; -- Eng
lin property_proprietà_CN = UseN property_N ; -- Eng
lin protocol_protocollo_CN = UseN protocol_N ; -- Eng
lin protocol_protocollo_CN = UseN protocol_N ; -- Eng
lin questions_domanda_CN = UseN questions_N ; -- Eng
oper questions_N = mkN "questions" ; -- Eng
lin reference_di_riferimento_CN = UseN reference_N ; -- Eng
lin reference_riferimento_CN = UseN reference_N ; -- Eng
lin reference_c_CN = UseN reference_N ; -- Eng
lin registration_con_CN = UseN registration_N ; -- Eng
lin regulation_regolamento_CN = UseN regulation_N ; -- Eng
lin representation_cennio_CN = UseN representation_N ; -- Eng
lin representation_rappresentazione_CN = UseN representation_N ; -- Eng
lin request_richiesta_CN = UseN request_N ; -- Eng
lin respect_topologia_CN = UseN respect_N ; -- Eng
lin restriction_restrizioni_CN = UseN restriction_N ; -- Eng
lin result_topologia_CN = UseN result_N ; -- Eng
lin review_Ripasso_CN = UseN review_N ; -- Eng
lin rule_regola_CN = UseN rule_N ; -- Eng
lin saturation_di_il_saturazione_CN = UseN saturation_N ; -- Eng
lin saturation_saturazione_CN = UseN saturation_N ; -- Eng
lin search_ricerca_CN = UseN search_N ; -- Eng
lin sector_settore_CN = UseN sector_N ; -- Eng
lin seminar_seminario_CN = UseN seminar_N ; -- Eng
lin sequence_funzione_CN = UseN sequence_N ; -- Eng
lin series_serie_CN = UseN series_N ; -- Eng
lin series_Pearson_CN = UseN series_N ; -- Eng
lin service_servizio_CN = UseN service_N ; -- Eng
lin sessions_appello_CN = UseN sessions_N ; -- Eng
oper sessions_N = mkN "sessions" ; -- Eng
lin set_Insiema_CN = UseN set_N ; -- Eng
lin set_Insiemo_CN = UseN set_N ; -- Eng
lin skills_critico_capacità_CN = UseN skills_N ; -- Eng
oper skills_N = mkN "skills" ; -- Eng
lin skills_capacità_CN = UseN skills_N ; -- Eng
oper skills_N = mkN "skills" ; -- Eng
lin slide_slide_CN = UseN slide_N ; -- Eng
lin solution_soluzione_CN = UseN solution_N ; -- Eng
lin solution_soluzioni_CN = UseN solution_N ; -- Eng
lin stability_concetto_CN = UseN stability_N ; -- Eng
lin stability_introduzione_CN = UseN stability_N ; -- Eng
lin state_essere_CN = UseN state_N ; -- Eng
lin statement_statements_CN = UseN statement_N ; -- Eng
lin student_il_studente_CN = UseN student_N ; -- Eng
lin student_a_il_studente_CN = UseN student_N ; -- Eng
lin student_accesso_CN = UseN student_N ; -- Eng
lin student_corso_CN = UseN student_N ; -- Eng
lin student_studente_CN = UseN student_N ; -- Eng
lin student_supporto_CN = UseN student_N ; -- Eng
lin student_ù_CN = UseN student_N ; -- Eng
lin synthesis_sintesi_CN = UseN synthesis_N ; -- Eng
lin system_sistema_CN = UseN system_N ; -- Eng
lin systems_Approfondimento_CN = UseN systems_N ; -- Eng
oper systems_N = mkN "systems" ; -- Eng
lin systems_ambiente_CN = UseN systems_N ; -- Eng
oper systems_N = mkN "systems" ; -- Eng
lin talk_orale_CN = UseN talk_N ; -- Eng
lin teacher_docente_CN = UseN teacher_N ; -- Eng
lin teacher_docento_CN = UseN teacher_N ; -- Eng
lin technique_tecnica_CN = UseN technique_N ; -- Eng
lin techniques_metodo_CN = UseN techniques_N ; -- Eng
oper techniques_N = mkN "techniques" ; -- Eng
lin termination_Terminazione_CN = UseN termination_N ; -- Eng
lin test_prova_CN = UseN test_N ; -- Eng
lin textbook_libro_CN = UseN textbook_N ; -- Eng
lin texts_testo_CN = UseN texts_N ; -- Eng
oper texts_N = mkN "texts" ; -- Eng
lin theorem_teorema_CN = UseN theorem_N ; -- Eng
lin theorey_teorema_CN = UseN theorey_N ; -- Eng
oper theorey_N = mkN "theorey" ; -- Eng
lin theory_teoria_CN = UseN theory_N ; -- Eng
lin thesis_classe_CN = UseN thesis_N ; -- Eng
lin thesis_tesi_CN = UseN thesis_N ; -- Eng
lin topic_esercizio_CN = UseN topic_N ; -- Eng
lin topics_recupero_CN = UseN topics_N ; -- Eng
oper topics_N = mkN "topics" ; -- Eng
lin topics_tema_CN = UseN topics_N ; -- Eng
oper topics_N = mkN "topics" ; -- Eng
lin topology_Topologia_CN = UseN topology_N ; -- Eng
lin topology_grafo_CN = UseN topology_N ; -- Eng
lin topology_risultato_CN = UseN topology_N ; -- Eng
lin tree_a_rinina_CN = UseN tree_N ; -- Eng
lin tutor_di_tutorato_CN = UseN tutor_N ; -- Eng
lin tutor_tutor_CN = UseN tutor_N ; -- Eng
lin tutor_tutoraggio_CN = UseN tutor_N ; -- Eng
lin type_attività_CN = UseN type_N ; -- Eng
lin type_tipo_CN = UseN type_N ; -- Eng
lin types_Types_CN = UseN types_N ; -- Eng
oper types_N = mkN "types" ; -- Eng
lin understande_comprensione_CN = UseN understande_N ; -- Eng
oper understande_N = mkN "understande" ; -- Eng
lin unit_insegnamento_CN = UseN unit_N ; -- Eng
lin unit_unità_CN = UseN unit_N ; -- Eng
lin unit_Learning_CN = UseN unit_N ; -- Eng
lin unit_NUMERICO_CN = UseN unit_N ; -- Eng
lin unit_and_CN = UseN unit_N ; -- Eng
lin unit_di_CN = UseN unit_N ; -- Eng
lin unit_orientare_CN = UseN unit_N ; -- Eng
lin use_uso_CN = UseN use_N ; -- Eng
lin variable_funzione_CN = UseN variable_N ; -- Eng
lin verification_verifica_CN = UseN verification_N ; -- Eng
lin write_scritta_CN = UseN write_N ; -- Eng
oper write_N = mkN "write" ; -- Eng
lin x_ciclo_CN = UseN x_N ; -- Eng
oper x_N = mkN "x" ; -- Eng
lin Antonio_Boccuto_Antonio_Boccere_NP = UsePN (FlatPN Antonio_PN Boccuto_PN) ; -- Eng
oper Antonio_PN = mkPN "Antonio" ; -- Eng
oper Boccuto_PN = mkPN "Boccuto" ; -- Eng
lin Arturo_Carpi_Arturo_Carpe_NP = UsePN (FlatPN Arturo_PN Carpi_PN) ; -- Eng
oper Arturo_PN = mkPN "Arturo" ; -- Eng
oper Carpi_PN = mkPN "Carpi" ; -- Eng
lin Celsius_pocket_Prinzm_NP = UsePN (FlatPN Celsius_PN pocket_PN) ; -- Eng
oper Celsius_PN = mkPN "Celsius" ; -- Eng
oper pocket_PN = mkPN "pocket" ; -- Eng
lin Marco_Bramanti_Bramare_Marco_NP = UsePN (FlatPN Marco_PN Bramanti_PN) ; -- Eng
oper Marco_PN = mkPN "Marco" ; -- Eng
oper Bramanti_PN = mkPN "Bramanti" ; -- Eng
lin Stefano_Marcugini_Marcugino_Stefare_NP = UsePN (FlatPN Stefano_PN Marcugini_PN) ; -- Eng
oper Stefano_PN = mkPN "Stefano" ; -- Eng
oper Marcugini_PN = mkPN "Marcugini" ; -- Eng
lin Valentina_Poggioni_Valentina_Poggioni_NP = UsePN (FlatPN Valentina_PN Poggioni_PN) ; -- Eng
oper Valentina_PN = mkPN "Valentina" ; -- Eng
oper Poggioni_PN = mkPN "Poggioni" ; -- Eng
lin ALGORITHMS_DISTRIBUTED_NP = UsePN ALGORITHMS_PN ; -- Eng
oper ALGORITHMS_PN = mkPN "ALGORITHMS" ; -- Eng
lin ARCHITECTURE_ARCHITETTURA_NP = UsePN ARCHITECTURE_PN ; -- Eng
oper ARCHITECTURE_PN = mkPN "ARCHITECTURE" ; -- Eng
lin Affine_integrativo_NP = UsePN Affine_PN ; -- Eng
oper Affine_PN = mkPN "Affine" ; -- Eng
lin Antonio_Antonio_NP = UsePN Antonio_PN ; -- Eng
oper Antonio_PN = mkPN "Antonio" ; -- Eng
lin Antonio_Boccere_NP = UsePN Antonio_PN ; -- Eng
oper Antonio_PN = mkPN "Antonio" ; -- Eng
lin Arturo_Carpe_NP = UsePN Arturo_PN ; -- Eng
oper Arturo_PN = mkPN "Arturo" ; -- Eng
lin Arturo_Arturo_NP = UsePN Arturo_PN ; -- Eng
oper Arturo_PN = mkPN "Arturo" ; -- Eng
lin Automi_Automo_NP = UsePN Automi_PN ; -- Eng
oper Automi_PN = mkPN "Automi" ; -- Eng
lin Barsi_Bare_NP = UsePN Barsi_PN ; -- Eng
oper Barsi_PN = mkPN "Barsi" ; -- Eng
lin Basics_Language_NP = UsePN Basics_PN ; -- Eng
oper Basics_PN = mkPN "Basics" ; -- Eng
lin Boccuto_Antonio_NP = UsePN Boccuto_PN ; -- Eng
oper Boccuto_PN = mkPN "Boccuto" ; -- Eng
lin Bolchini_Bolchino_NP = UsePN Bolchini_PN ; -- Eng
oper Bolchini_PN = mkPN "Bolchini" ; -- Eng
lin Bruno_Didattica_NP = UsePN Bruno_PN ; -- Eng
oper Bruno_PN = mkPN "Bruno" ; -- Eng
lin Bruno_Iannazzo_NP = UsePN Bruno_PN ; -- Eng
oper Bruno_PN = mkPN "Bruno" ; -- Eng
lin CORMEN_introduzione_NP = UsePN CORMEN_PN ; -- Eng
oper CORMEN_PN = mkPN "CORMEN" ; -- Eng
lin C_struttura_NP = UsePN C_PN ; -- Eng
oper C_PN = mkPN "C" ; -- Eng
lin C_Charu_NP = UsePN C_PN ; -- Eng
oper C_PN = mkPN "C" ; -- Eng
lin C_teoria_NP = UsePN C_PN ; -- Eng
oper C_PN = mkPN "C" ; -- Eng
lin Caratterizzante_Caratterizzare_NP = UsePN Caratterizzante_PN ; -- Eng
oper Caratterizzante_PN = mkPN "Caratterizzante" ; -- Eng
lin Carpi_Carpe_NP = UsePN Carpi_PN ; -- Eng
oper Carpi_PN = mkPN "Carpi" ; -- Eng
lin Cay_Cay_NP = UsePN Cay_PN ; -- Eng
oper Cay_PN = mkPN "Cay" ; -- Eng
lin Celsius_il_NP = UsePN Celsius_PN ; -- Eng
oper Celsius_PN = mkPN "Celsius" ; -- Eng
lin Celsius_linguaggio_NP = UsePN Celsius_PN ; -- Eng
oper Celsius_PN = mkPN "Celsius" ; -- Eng
lin Codocenza_Codocenza_NP = UsePN Codocenza_PN ; -- Eng
oper Codocenza_PN = mkPN "Codocenza" ; -- Eng
lin Computability_insegnamento_NP = UsePN Computability_PN ; -- Eng
oper Computability_PN = mkPN "Computability" ; -- Eng
lin Compute_Look_NP = UsePN Compute_PN ; -- Eng
oper Compute_PN = mkPN "Compute" ; -- Eng
lin Configurations_Configurazioni_NP = UsePN Configurations_PN ; -- Eng
oper Configurations_PN = mkPN "Configurations" ; -- Eng
lin Cook_Edmonds_NP = UsePN Cook_PN ; -- Eng
oper Cook_PN = mkPN "Cook" ; -- Eng
lin Cornell_Graw_NP = UsePN Cornell_PN ; -- Eng
oper Cornell_PN = mkPN "Cornell" ; -- Eng
lin Cristiana_Cristiana_NP = UsePN Cristiana_PN ; -- Eng
oper Cristiana_PN = mkPN "Cristiana" ; -- Eng
lin Cristina_Cristina_NP = UsePN Cristina_PN ; -- Eng
oper Cristina_PN = mkPN "Cristina" ; -- Eng
lin Custom_Science_NP = UsePN Custom_PN ; -- Eng
oper Custom_PN = mkPN "Custom" ; -- Eng
lin Davis_Davis_NP = UsePN Davis_PN ; -- Eng
oper Davis_PN = mkPN "Davis" ; -- Eng
lin Deitel_Pearson_NP = UsePN Deitel_PN ; -- Eng
oper Deitel_PN = mkPN "Deitel" ; -- Eng
lin Didattica_Didattica_NP = UsePN Didattica_PN ; -- Eng
oper Didattica_PN = mkPN "Didattica" ; -- Eng
lin Didattica_Iannazzo_NP = UsePN Didattica_PN ; -- Eng
oper Didattica_PN = mkPN "Didattica" ; -- Eng
lin Didattica_ore_NP = UsePN Didattica_PN ; -- Eng
oper Didattica_PN = mkPN "Didattica" ; -- Eng
lin Didattica_ufficiale_NP = UsePN Didattica_PN ; -- Eng
oper Didattica_PN = mkPN "Didattica" ; -- Eng
lin Distributed_ambiente_NP = UsePN Distributed_PN ; -- Eng
oper Distributed_PN = mkPN "Distributed" ; -- Eng
lin Dyslexia_Dislessia_NP = UsePN Dyslexia_PN ; -- Eng
oper Dyslexia_PN = mkPN "Dyslexia" ; -- Eng
lin EXAMPLES_esempio_NP = UsePN EXAMPLES_PN ; -- Eng
oper EXAMPLES_PN = mkPN "EXAMPLES" ; -- Eng
lin Ebook_Booktab_NP = UsePN Ebook_PN ; -- Eng
oper Ebook_PN = mkPN "Ebook" ; -- Eng
lin English_inglese_NP = UsePN English_PN ; -- Eng
oper English_PN = mkPN "English" ; -- Eng
lin Esercitazioni_Esercitazione_NP = UsePN Esercitazioni_PN ; -- Eng
oper Esercitazioni_PN = mkPN "Esercitazioni" ; -- Eng
lin F_f_NP = UsePN F_PN ; -- Eng
oper F_PN = mkPN "F" ; -- Eng
lin Francesco_Francesco_NP = UsePN Francesco_PN ; -- Eng
oper Francesco_PN = mkPN "Francesco" ; -- Eng
lin Francesco_ufficiale_NP = UsePN Francesco_PN ; -- Eng
oper Francesco_PN = mkPN "Francesco" ; -- Eng
lin GCC_GCC_NP = UsePN GCC_PN ; -- Eng
oper GCC_PN = mkPN "GCC" ; -- Eng
lin GDB_GDB_NP = UsePN GDB_PN ; -- Eng
oper GDB_PN = mkPN "GDB" ; -- Eng
lin Gary_Cay_NP = UsePN Gary_PN ; -- Eng
oper Gary_PN = mkPN "Gary" ; -- Eng
lin Gentilini_Didattica_NP = UsePN Gentilini_PN ; -- Eng
oper Gentilini_PN = mkPN "Gentilini" ; -- Eng
lin Hill_Hill_NP = UsePN Hill_PN ; -- Eng
oper Hill_PN = mkPN "Hill" ; -- Eng
lin Hill_Toffalore_NP = UsePN Hill_PN ; -- Eng
oper Hill_PN = mkPN "Hill" ; -- Eng
lin Horstmann_Horstmann_NP = UsePN Horstmann_PN ; -- Eng
oper Horstmann_PN = mkPN "Horstmann" ; -- Eng
lin Hypercube_di_il_ipercubo_NP = UsePN Hypercube_PN ; -- Eng
oper Hypercube_PN = mkPN "Hypercube" ; -- Eng
lin Iannazzo_ufficiale_NP = UsePN Iannazzo_PN ; -- Eng
oper Iannazzo_PN = mkPN "Iannazzo" ; -- Eng
lin Italian_lingua_NP = UsePN Italian_PN ; -- Eng
oper Italian_PN = mkPN "Italian" ; -- Eng
lin JAVA_il_NP = UsePN JAVA_PN ; -- Eng
oper JAVA_PN = mkPN "JAVA" ; -- Eng
lin Java_java_NP = UsePN Java_PN ; -- Eng
oper Java_PN = mkPN "Java" ; -- Eng
lin Java_Core_NP = UsePN Java_PN ; -- Eng
oper Java_PN = mkPN "Java" ; -- Eng
lin Karpatne_Karpatne_NP = UsePN Karpatne_PN ; -- Eng
oper Karpatne_PN = mkPN "Karpatne" ; -- Eng
lin Kirch_Pages_NP = UsePN Kirch_PN ; -- Eng
oper Kirch_PN = mkPN "Kirch" ; -- Eng
lin Kumar_Kumar_NP = UsePN Kumar_PN ; -- Eng
oper Kumar_PN = mkPN "Kumar" ; -- Eng
lin Language_linguaggio_NP = UsePN Language_PN ; -- Eng
oper Language_PN = mkPN "Language" ; -- Eng
lin Learning_MACHINE_NP = UsePN Learning_PN ; -- Eng
oper Learning_PN = mkPN "Learning" ; -- Eng
lin Logiche_Logico_NP = UsePN Logiche_PN ; -- Eng
oper Logiche_PN = mkPN "Logiche" ; -- Eng
lin Manjikian_McGraw_NP = UsePN Manjikian_PN ; -- Eng
oper Manjikian_PN = mkPN "Manjikian" ; -- Eng
lin Marco_Carlo_NP = UsePN Marco_PN ; -- Eng
oper Marco_PN = mkPN "Marco" ; -- Eng
lin Marco_Bramare_NP = UsePN Marco_PN ; -- Eng
oper Marco_PN = mkPN "Marco" ; -- Eng
lin Marcugini_Marcugino_NP = UsePN Marcugini_PN ; -- Eng
oper Marcugini_PN = mkPN "Marcugini" ; -- Eng
lin Maria_Maria_NP = UsePN Maria_PN ; -- Eng
oper Maria_PN = mkPN "Maria" ; -- Eng
lin McGraw_f_NP = UsePN McGraw_PN ; -- Eng
oper McGraw_PN = mkPN "McGraw" ; -- Eng
lin Module_secondo_NP = UsePN Module_PN ; -- Eng
oper Module_PN = mkPN "Module" ; -- Eng
lin Monge_di_Monge_NP = UsePN Monge_PN ; -- Eng
oper Monge_PN = mkPN "Monge" ; -- Eng
lin NUMERICAL_insegnamento_NP = UsePN NUMERICAL_PN ; -- Eng
oper NUMERICAL_PN = mkPN "NUMERICAL" ; -- Eng
lin Naraig_introduzione_NP = UsePN Naraig_PN ; -- Eng
oper Naraig_PN = mkPN "Naraig" ; -- Eng
lin Navarra_ore_NP = UsePN Navarra_PN ; -- Eng
oper Navarra_PN = mkPN "Navarra" ; -- Eng
lin Navarra_Alfredere_NP = UsePN Navarra_PN ; -- Eng
oper Navarra_PN = mkPN "Navarra" ; -- Eng
lin Niclà_Nicla_NP = UsePN Niclà_PN ; -- Eng
oper Niclà_PN = mkPN "Niclà" ; -- Eng
lin P_p_NP = UsePN P_PN ; -- Eng
oper P_PN = mkPN "P" ; -- Eng
lin Pagine_Pagine_NP = UsePN Pagine_PN ; -- Eng
oper Pagine_PN = mkPN "Pagine" ; -- Eng
lin Paola_Paola_NP = UsePN Paola_PN ; -- Eng
oper Paola_PN = mkPN "Paola" ; -- Eng
lin Pearson_Pearson_NP = UsePN Pearson_PN ; -- Eng
oper Pearson_PN = mkPN "Pearson" ; -- Eng
lin Pearson_computer_NP = UsePN Pearson_PN ; -- Eng
oper Pearson_PN = mkPN "Pearson" ; -- Eng
lin Peter_Peter_NP = UsePN Peter_PN ; -- Eng
oper Peter_PN = mkPN "Peter" ; -- Eng
lin Pinotti_Didattica_NP = UsePN Pinotti_PN ; -- Eng
oper Pinotti_PN = mkPN "Pinotti" ; -- Eng
lin Pinotti_Pinurre_NP = UsePN Pinotti_PN ; -- Eng
oper Pinotti_PN = mkPN "Pinotti" ; -- Eng
lin Pipelining_Pipelining_NP = UsePN Pipelining_PN ; -- Eng
oper Pipelining_PN = mkPN "Pipelining" ; -- Eng
lin Poggioni_Didattica_NP = UsePN Poggioni_PN ; -- Eng
oper Poggioni_PN = mkPN "Poggioni" ; -- Eng
lin Preflow_Matching_NP = UsePN Preflow_PN ; -- Eng
oper Preflow_PN = mkPN "Preflow" ; -- Eng
lin Prinz_Prinz_NP = UsePN Prinz_PN ; -- Eng
oper Prinz_PN = mkPN "Prinz" ; -- Eng
lin Probability_probabilità_NP = UsePN Probability_PN ; -- Eng
oper Probability_PN = mkPN "Probability" ; -- Eng
lin Procedural_programmazione_NP = UsePN Procedural_PN ; -- Eng
oper Procedural_PN = mkPN "Procedural" ; -- Eng
lin Raffaellà_Raffaello_NP = UsePN Raffaellà_PN ; -- Eng
oper Raffaellà_PN = mkPN "Raffaellà" ; -- Eng
lin Reti_rete_NP = UsePN Reti_PN ; -- Eng
oper Reti_PN = mkPN "Reti" ; -- Eng
lin Rubbioni_Didattica_NP = UsePN Rubbioni_PN ; -- Eng
oper Rubbioni_PN = mkPN "Rubbioni" ; -- Eng
lin Rubbioni_Rubbioni_NP = UsePN Rubbioni_PN ; -- Eng
oper Rubbioni_PN = mkPN "Rubbioni" ; -- Eng
lin SMAWK_di_il_massimo_NP = UsePN SMAWK_PN ; -- Eng
oper SMAWK_PN = mkPN "SMAWK" ; -- Eng
lin Salsa_Domenico_NP = UsePN Salsa_PN ; -- Eng
oper Salsa_PN = mkPN "Salsa" ; -- Eng
lin Santini_Francesco_NP = UsePN Santini_PN ; -- Eng
oper Santini_PN = mkPN "Santini" ; -- Eng
lin Santini_Santino_NP = UsePN Santini_PN ; -- Eng
oper Santini_PN = mkPN "Santini" ; -- Eng
lin Santoro_N_NP = UsePN Santoro_PN ; -- Eng
oper Santoro_PN = mkPN "Santoro" ; -- Eng
lin Sergio_tasso_NP = UsePN Sergio_PN ; -- Eng
oper Sergio_PN = mkPN "Sergio" ; -- Eng
lin Sergio_Sergio_NP = UsePN Sergio_PN ; -- Eng
oper Sergio_PN = mkPN "Sergio" ; -- Eng
lin Stefano_Stefare_NP = UsePN Stefano_PN ; -- Eng
oper Stefano_PN = mkPN "Stefano" ; -- Eng
lin Steinbach_Steinbach_NP = UsePN Steinbach_PN ; -- Eng
oper Steinbach_PN = mkPN "Steinbach" ; -- Eng
lin Tan_Tan_NP = UsePN Tan_PN ; -- Eng
oper Tan_PN = mkPN "Tan" ; -- Eng
lin Tasso_ufficiale_NP = UsePN Tasso_PN ; -- Eng
oper Tasso_PN = mkPN "Tasso" ; -- Eng
lin Turing_universale_NP = UsePN Turing_PN ; -- Eng
oper Turing_PN = mkPN "Turing" ; -- Eng
lin Ufficiale_Didattica_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_Pinotto_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_Rubbioni_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_Santino_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_ore_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_ufficiale_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_Arturo_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Ufficiale_Stefare_NP = UsePN Ufficiale_PN ; -- Eng
oper Ufficiale_PN = mkPN "Ufficiale" ; -- Eng
lin Unistudium_Unistudium_NP = UsePN Unistudium_PN ; -- Eng
oper Unistudium_PN = mkPN "Unistudium" ; -- Eng
lin Valentina_Poggioni_NP = UsePN Valentina_PN ; -- Eng
oper Valentina_PN = mkPN "Valentina" ; -- Eng
lin Versioning_versionamento_NP = UsePN Versioning_PN ; -- Eng
oper Versioning_PN = mkPN "Versioning" ; -- Eng
lin Zaky_Zaky_NP = UsePN Zaky_PN ; -- Eng
oper Zaky_PN = mkPN "Zaky" ; -- Eng
lin Zanichelli_Zanichelli_NP = UsePN Zanichelli_PN ; -- Eng
oper Zanichelli_PN = mkPN "Zanichelli" ; -- Eng
lin advanced_insegnamento_NP = UsePN advanced_PN ; -- Eng
oper advanced_PN = mkPN "advanced" ; -- Eng
lin analysis_CALCOLO_NP = UsePN analysis_PN ; -- Eng
oper analysis_PN = mkPN "analysis" ; -- Eng
lin analysis_matematica_NP = UsePN analysis_PN ; -- Eng
oper analysis_PN = mkPN "analysis" ; -- Eng
lin and_ADVANCED_NP = UsePN and_PN ; -- Eng
oper and_PN = mkPN "and" ; -- Eng
lin area_ambito_NP = UsePN area_PN ; -- Eng
oper area_PN = mkPN "area" ; -- Eng
lin church_Church_NP = UsePN church_PN ; -- Eng
oper church_PN = mkPN "church" ; -- Eng
lin computer_insegnamento_NP = UsePN computer_PN ; -- Eng
oper computer_PN = mkPN "computer" ; -- Eng
lin computer_Architettura_NP = UsePN computer_PN ; -- Eng
oper computer_PN = mkPN "computer" ; -- Eng
lin computer_informatica_NP = UsePN computer_PN ; -- Eng
oper computer_PN = mkPN "computer" ; -- Eng
lin election_leadere_NP = UsePN election_PN ; -- Eng
oper election_PN = mkPN "election" ; -- Eng
lin entities_Entità_NP = UsePN entities_PN ; -- Eng
oper entities_PN = mkPN "entities" ; -- Eng
lin events_evente_NP = UsePN events_PN ; -- Eng
oper events_PN = mkPN "events" ; -- Eng
lin hours_Arturo_NP = UsePN hours_PN ; -- Eng
oper hours_PN = mkPN "hours" ; -- Eng
lin hours_Boccere_NP = UsePN hours_PN ; -- Eng
oper hours_PN = mkPN "hours" ; -- Eng
lin hours_Stefare_NP = UsePN hours_PN ; -- Eng
oper hours_PN = mkPN "hours" ; -- Eng
lin laboratory_laboratorio_NP = UsePN laboratory_PN ; -- Eng
oper laboratory_PN = mkPN "laboratory" ; -- Eng
lin look_modello_NP = UsePN look_PN ; -- Eng
oper look_PN = mkPN "look" ; -- Eng
lin machine_di_macchina_NP = UsePN machine_PN ; -- Eng
oper machine_PN = mkPN "machine" ; -- Eng
lin machine_insegnamento_NP = UsePN machine_PN ; -- Eng
oper machine_PN = mkPN "machine" ; -- Eng
lin mathematical_analiso_NP = UsePN mathematical_PN ; -- Eng
oper mathematical_PN = mkPN "mathematical" ; -- Eng
lin model_Compere_NP = UsePN model_PN ; -- Eng
oper model_PN = mkPN "model" ; -- Eng
lin move_Move_NP = UsePN move_PN ; -- Eng
oper move_PN = mkPN "move" ; -- Eng
lin object_il_NP = UsePN object_PN ; -- Eng
oper object_PN = mkPN "object" ; -- Eng
lin oriented_Ad_NP = UsePN oriented_PN ; -- Eng
oper oriented_PN = mkPN "oriented" ; -- Eng
lin oriented_oggetti_NP = UsePN oriented_PN ; -- Eng
oper oriented_PN = mkPN "oriented" ; -- Eng
lin pages_programmazione_NP = UsePN pages_PN ; -- Eng
oper pages_PN = mkPN "pages" ; -- Eng
lin problem_flusso_NP = UsePN problem_PN ; -- Eng
oper problem_PN = mkPN "problem" ; -- Eng
lin program_programma_NP = UsePN program_PN ; -- Eng
oper program_PN = mkPN "program" ; -- Eng
lin programme_PROCEDURALE_NP = UsePN programme_PN ; -- Eng
oper programme_PN = mkPN "programme" ; -- Eng
lin programming_con_NP = UsePN programming_PN ; -- Eng
oper programming_PN = mkPN "programming" ; -- Eng
lin programming_oggetti_NP = UsePN programming_PN ; -- Eng
oper programming_PN = mkPN "programming" ; -- Eng
lin programming_programmazione_NP = UsePN programming_PN ; -- Eng
oper programming_PN = mkPN "programming" ; -- Eng
lin required_Required_NP = UsePN required_PN ; -- Eng
oper required_PN = mkPN "required" ; -- Eng
lin responsible_si_NP = UsePN responsible_PN ; -- Eng
oper responsible_PN = mkPN "responsible" ; -- Eng
lin science_Library_NP = UsePN science_PN ; -- Eng
oper science_PN = mkPN "science" ; -- Eng
lin share_condividere_NP = UsePN share_PN ; -- Eng
oper share_PN = mkPN "share" ; -- Eng
lin statistics_Statistica_NP = UsePN statistics_PN ; -- Eng
oper statistics_PN = mkPN "statistics" ; -- Eng
lin structures_Structures_NP = UsePN structures_PN ; -- Eng
oper structures_PN = mkPN "structures" ; -- Eng
lin supply_Erogare_NP = UsePN supply_PN ; -- Eng
oper supply_PN = mkPN "supply" ; -- Eng
lin systems_Distribuire_NP = UsePN systems_PN ; -- Eng
oper systems_PN = mkPN "systems" ; -- Eng
lin unions_Unions_NP = UsePN unions_PN ; -- Eng
oper unions_PN = mkPN "unions" ; -- Eng
lin whole_il_NP = UsePN whole_PN ; -- Eng
oper whole_PN = mkPN "whole" ; -- Eng
lin with_con_NP = UsePN with_PN ; -- Eng
oper with_PN = mkPN "with" ; -- Eng
lin with_laboratorio_NP = UsePN with_PN ; -- Eng
oper with_PN = mkPN "with" ; -- Eng
lin solvable_Algorithmically_risolubile_Utt = UttVP (AdvVP (UseAP (PositA solvable_A)) Algorithmically_Adv) ; -- Eng
oper Algorithmically_Adv = mkAdv "Algorithmically" ; -- Eng
lin course_regulation_regolamento_Utt = UttVP (ComplV course_V (PluralNP (UseN regulation_N))) ; -- Eng
lin extend_program_programma_esteso_Utt = UttVP (ComplV extend_V (PluralNP (UseN program_N))) ; -- Eng
lin Algorithms_conoscenza_V = Algorithms_V ; -- Eng
oper Algorithms_V = mkV "Algorithms" ; -- Eng
lin Broadcasting_Broadcasting_V = Broadcasting_V ; -- Eng
oper Broadcasting_V = mkV "Broadcasting" ; -- Eng
lin Compil_Compilazione_V = Compil_V ; -- Eng
oper Compil_V = mkV "Compil" ; -- Eng
lin Comuno_comune_V = Comuno_V ; -- Eng
oper Comuno_V = mkV "Comuno" ; -- Eng
lin Debugge_Debugging_V = Debugge_V ; -- Eng
oper Debugge_V = mkV "Debugge" ; -- Eng
lin Distribute_distribuita_V = Distribute_V ; -- Eng
oper Distribute_V = mkV "Distribute" ; -- Eng
lin Flood_Algoritmo_V = Flood_V ; -- Eng
oper Flood_V = mkV "Flood" ; -- Eng
lin Gather_problema_V = Gather_V ; -- Eng
oper Gather_V = mkV "Gather" ; -- Eng
lin Gather_Gathering_V = Gather_V ; -- Eng
oper Gather_V = mkV "Gather" ; -- Eng
lin Learn_Conoscere_V = Learn_V ; -- Eng
oper Learn_V = mkV "Learn" ; -- Eng
lin Multithreading_Multithreading_V = Multithreading_V ; -- Eng
oper Multithreading_V = mkV "Multithreading" ; -- Eng
lin Np_problema_V = Np_V ; -- Eng
oper Np_V = mkV "Np" ; -- Eng
lin Spanning_Spanning_V = Spanning_V ; -- Eng
oper Spanning_V = mkV "Spanning" ; -- Eng
lin Spanning_trea_V = Spanning_V ; -- Eng
oper Spanning_V = mkV "Spanning" ; -- Eng
lin Supervize_approccio_V = Supervize_V ; -- Eng
oper Supervize_V = mkV "Supervize" ; -- Eng
lin Tur_macchina_V = Tur_V ; -- Eng
oper Tur_V = mkV "Tur" ; -- Eng
lin Turing_macchina_V = Turing_V ; -- Eng
oper Turing_V = mkV "Turing" ; -- Eng
lin Wake_problema_V = Wake_V ; -- Eng
oper Wake_V = mkV "Wake" ; -- Eng
lin Wake_Up_V = Wake_V ; -- Eng
oper Wake_V = mkV "Wake" ; -- Eng
lin Wake_Wake_V = Wake_V ; -- Eng
oper Wake_V = mkV "Wake" ; -- Eng
lin acquire_acquisire_V = acquire_V ; -- Eng
lin advance_avanzare_V = advance_V ; -- Eng
lin advance_combinatorico_V = advance_V ; -- Eng
lin aim_finalizzare_V = aim_V ; -- Eng
lin aim_proporre_V = aim_V ; -- Eng
lin allow_consentire_V = allow_V ; -- Eng
lin apply_applicare_V = apply_V ; -- Eng
lin ask_porre_V = ask_V ; -- Eng
lin attend_seguire_V = attend_V ; -- Eng
lin avail_corso_V = avail_V ; -- Eng
lin base_banere_V = base_V ; -- Eng
lin be_colloquio_V = be_V ; -- Eng
oper be_V = mkV "be" ; -- Eng
lin be_quello_V = be_V ; -- Eng
oper be_V = mkV "be" ; -- Eng
lin build_realizzare_V = build_V ; -- Eng
lin carry_svogliere_V = carry_V ; -- Eng
lin code_Codifica_V = code_V ; -- Eng
lin compare_comparare_V = compare_V ; -- Eng
lin concrete_concreto_V = concrete_V ; -- Eng
lin control_elaboratore_V = control_V ; -- Eng
oper control_V = mkV "control" ; -- Eng
lin count_contare_V = count_V ; -- Eng
lin covere_trattare_V = covere_V ; -- Eng
oper covere_V = mkV "covere" ; -- Eng
lin create_realizzare_V = create_V ; -- Eng
lin deep_Deep_V = deep_V ; -- Eng
oper deep_V = mkV "deep" ; -- Eng
lin discuss_discutere_V = discuss_V ; -- Eng
lin establish_organizzare_V = establish_V ; -- Eng
lin explore_approfondere_V = explore_V ; -- Eng
lin expose_esporre_V = expose_V ; -- Eng
lin extend_esteso_V = extend_V ; -- Eng
lin face_lezione_V = face_V ; -- Eng
lin find_triangulation_V = find_V ; -- Eng
lin find_Closest_V = find_V ; -- Eng
lin flow_bipartire_V = flow_V ; -- Eng
lin generalize_generalizzato_V = generalize_V ; -- Eng
lin get_capacità_V = get_V ; -- Eng
oper get_V = mkV "get" ; -- Eng
lin give_fornire_V = give_V ; -- Eng
oper give_V = mkV "give" ; -- Eng
lin give_tenere_V = give_V ; -- Eng
oper give_V = mkV "give" ; -- Eng
lin give_valutare_V = give_V ; -- Eng
oper give_V = mkV "give" ; -- Eng
lin halt_problema_V = halt_V ; -- Eng
lin have_opportuno_V = have_V ; -- Eng
lin implement_realizzare_V = implement_V ; -- Eng
lin increas_Accrescimento_V = increas_V ; -- Eng
oper increas_V = mkV "increas" ; -- Eng
lin involve_prevedere_V = involve_V ; -- Eng
lin know_calcolare_V = know_V ; -- Eng
lin know_sapere_V = know_V ; -- Eng
lin machine_macchina_V = machine_V ; -- Eng
lin machine_macchina_V = machine_V ; -- Eng
lin make_commettere_V = make_V ; -- Eng
lin need_educativo_V = need_V ; -- Eng
lin note_dispense_V = note_V ; -- Eng
lin object_programmazione_V = object_V ; -- Eng
lin object_orientare_V = object_V ; -- Eng
lin obtain_conseguire_V = obtain_V ; -- Eng
lin plan_prevedere_V = plan_V ; -- Eng
lin prepare_preparare_V = prepare_V ; -- Eng
lin present_presentare_V = present_V ; -- Eng
lin present_presentare_V = present_V ; -- Eng
lin provide_fornire_V = provide_V ; -- Eng
lin relate_relazionare_V = relate_V ; -- Eng
lin revisit_rivisitare_V = revisit_V ; -- Eng
lin scope_noma_V = scope_V ; -- Eng
oper scope_V = mkV "scope" ; -- Eng
lin see_Calendario_V = see_V ; -- Eng
lin solve_solving_problem_V = solve_V ; -- Eng
lin suggest_consigliare_V = suggest_V ; -- Eng
lin supplie_Coorte_V = supplie_V ; -- Eng
oper supplie_V = mkV "supplie" ; -- Eng
lin take_sostenere_V = take_V ; -- Eng
oper take_V = mkV "take" ; -- Eng
lin take_svolgere_V = take_V ; -- Eng
oper take_V = mkV "take" ; -- Eng
lin teaching_insegnamento_V = teaching_V ; -- Eng
oper teaching_V = mkV "teaching" ; -- Eng
lin use_utilizzare_V = use_V ; -- Eng
lin versione_licenza_V = versione_V ; -- Eng
oper versione_V = mkV "versione" ; -- Eng
lin versione_versione_V = versione_V ; -- Eng
oper versione_V = mkV "versione" ; -- Eng
lin work_lavorare_V = work_V ; -- Eng
lin write_prevedere_V = write_V ; -- Eng
lin able_grado_A = able_A ; -- Eng
lin able_effettuare_A = able_A ; -- Eng
lin addition_materiale_A = addition_A ; -- Eng
oper addition_A = mkA "addition" ; -- Eng
lin advance_avanzato_A = advance_A ; -- Eng
oper advance_A = mkA "advance" ; -- Eng
lin affini_integrativo_Adv = affini_Adv ; -- Eng
oper affini_Adv = mkAdv "affini" ; -- Eng
lin also_anche_Adv = also_Adv ; -- Eng
lin also_inoltre_Adv = also_Adv ; -- Eng
lin anomaly_detection_A = anomaly_A ; -- Eng
oper anomaly_A = mkA "anomaly" ; -- Eng
lin architecture_architettura_Adv = architecture_Adv ; -- Eng
oper architecture_Adv = mkAdv "architecture" ; -- Eng
lin array_Array_Adv = array_Adv ; -- Eng
oper array_Adv = mkAdv "array" ; -- Eng
lin assembly_linguaggio_Adv = assembly_Adv ; -- Eng
oper assembly_Adv = mkAdv "assembly" ; -- Eng
lin assigned_scritto_A = assigned_A ; -- Eng
oper assigned_A = mkA "assigned" ; -- Eng
lin available_disponibile_A = available_A ; -- Eng
lin basic_di_programmazione_A = basic_A ; -- Eng
lin best_migliore_A = best_A ; -- Eng
lin classic_classico_A = classic_A ; -- Eng
lin code_codice_Prep = code_Prep ; -- Eng
oper code_Prep = mkPrep "code" ; -- Eng
lin collaborative_generale_A = collaborative_A ; -- Eng
lin complete_completo_A = complete_A ; -- Eng
lin computational_numerico_A = computational_A ; -- Eng
lin constructivist_comportamentista_A = constructivist_A ; -- Eng
oper constructivist_A = mkA "constructivist" ; -- Eng
lin critical_capacità_A = critical_A ; -- Eng
lin derivative_derivato_A = derivative_A ; -- Eng
lin derivative_valore_A = derivative_A ; -- Eng
lin di_analiso_Adv = di_Adv ; -- Eng
oper di_Adv = mkAdv "di" ; -- Eng
lin double_Integrale_A = double_A ; -- Eng
lin dynamic_dinamico_A = dynamic_A ; -- Eng
lin dyscalculia_discalculia_Adv = dyscalculia_Adv ; -- Eng
oper dyscalculia_Adv = mkAdv "dyscalculia" ; -- Eng
lin education_specali_A = education_A ; -- Eng
oper education_A = mkA "education" ; -- Eng
lin familiar_avere_A = familiar_A ; -- Eng
lin fdirst_di_base_Adv = fdirst_Adv ; -- Eng
oper fdirst_Adv = mkAdv "fdirst" ; -- Eng
lin fifteen_quindici_circa_Adv = fifteen_Adv ; -- Eng
oper fifteen_Adv = mkAdv "fifteen" ; -- Eng
lin final_finale_A = final_A ; -- Eng
lin finally_infine_Adv = finally_Adv ; -- Eng
oper finally_Adv = mkAdv "finally" ; -- Eng
lin fondamenti_Mc_Adv = fondamenti_Adv ; -- Eng
oper fondamenti_Adv = mkAdv "fondamenti" ; -- Eng
lin frequent_frequente_A = frequent_A ; -- Eng
lin functional_funzionale_A = functional_A ; -- Eng
lin fundamental_fondamentale_A = fundamental_A ; -- Eng
lin further_di_teoria_A = further_A ; -- Eng
lin general_di_il_disciplina_A = general_A ; -- Eng
lin general_generale_A = general_A ; -- Eng
lin hull_Covex_Adv = hull_Adv ; -- Eng
oper hull_Adv = mkAdv "hull" ; -- Eng
lin important_puntatore_A = important_A ; -- Eng
lin important_importante_A = important_A ; -- Eng
lin in_profitto_Prep = in_Prep ; -- Eng
lin inclusive_comprensivo_A = inclusive_A ; -- Eng
lin inevitable_inevitabile_A = inevitable_A ; -- Eng
lin informatica_informatico_Adv = informatica_Adv ; -- Eng
oper informatica_Adv = mkAdv "informatica" ; -- Eng
lin integrative_attività_A = integrative_A ; -- Eng
lin lab_pratico_A = lab_A ; -- Eng
oper lab_A = mkA "lab" ; -- Eng
lin listen_di_ascolgere_A = listen_A ; -- Eng
oper listen_A = mkA "listen" ; -- Eng
lin local_locale_A = local_A ; -- Eng
lin logic_logico_A = logic_A ; -- Eng
oper logic_A = mkA "logic" ; -- Eng
lin lower_numerico_A = lower_A ; -- Eng
oper lower_A = mkA "lower" ; -- Eng
lin material_eventuale_A = material_A ; -- Eng
lin material_dispense_A = material_A ; -- Eng
lin mathematical_metodologico_A = mathematical_A ; -- Eng
lin monodisciplinare_monodisciplinare_Adv = monodisciplinare_Adv ; -- Eng
oper monodisciplinare_Adv = mkAdv "monodisciplinare" ; -- Eng
lin most_più_Adv = most_Adv ; -- Eng
lin multiple_multiple_A = multiple_A ; -- Eng
lin not_similare_Adv = not_Adv ; -- Eng
oper not_Adv = mkAdv "not" ; -- Eng
lin numerical_elementare_A = numerical_A ; -- Eng
lin o_formativo_Adv = o_Adv ; -- Eng
oper o_Adv = mkAdv "o" ; -- Eng
lin oral_esame_A = oral_A ; -- Eng
lin oral_orale_A = oral_A ; -- Eng
lin other_altro_A = other_A ; -- Eng
lin particular_particolare_A = particular_A ; -- Eng
lin period_periodo_Adv = period_Adv ; -- Eng
oper period_Adv = mkAdv "period" ; -- Eng
lin personal_personale_A = personal_A ; -- Eng
lin possible_dispositivo_A = possible_A ; -- Eng
lin possible_essere_A = possible_A ; -- Eng
lin possible_possibili_A = possible_A ; -- Eng
lin psychological_psicologico_A = psychological_A ; -- Eng
lin recursive_ricorsivere_A = recursive_A ; -- Eng
lin related_dettagliato_A = related_A ; -- Eng
oper related_A = mkA "related" ; -- Eng
lin second_secondo_Semestre_A = second_A ; -- Eng
oper second_A = mkA "second" ; -- Eng
lin strongly_fortemente_Adv = strongly_Adv ; -- Eng
oper strongly_Adv = mkAdv "strongly" ; -- Eng
lin student_di_il_studente_A = student_A ; -- Eng
oper student_A = mkA "student" ; -- Eng
lin theoretic_teorico_A = theoretic_A ; -- Eng
lin three_tre_Adv = three_Adv ; -- Eng
oper three_Adv = mkAdv "three" ; -- Eng
lin two_due_Adv = two_Adv ; -- Eng
oper two_Adv = mkAdv "two" ; -- Eng
lin unico_unico_A = unico_A ; -- Eng
oper unico_A = mkA "unico" ; -- Eng
lin unique_unico_A = unique_A ; -- Eng
lin unsolvable_insolubile_A = unsolvable_A ; -- Eng
oper unsolvable_A = mkA "unsolvable" ; -- Eng
lin upper_estere_A = upper_A ; -- Eng
lin useful_utile_A = useful_A ; -- Eng
lin variable_medio_A = variable_A ; -- Eng
lin variable_variabile_A = variable_A ; -- Eng
lin various_vario_A = various_A ; -- Eng
} -- Eng
